export component WallpaperCard {
    in property <image> file-url;
    in property <bool> is-video;
    in property <bool> is-current;
    in property <length> card-w-nc;
    in property <length> card-w-c;
    in property <length> card-h-nc;
    in property <length> card-h-c;

    callback clicked;

    property <length> card-w: is-current ? card-w-c : card-w-nc;
    property <length> card-h: is-current ? card-h-c : card-h-nc;
    width: card-w;
    height: card-h;

    animate width {
        duration: 400ms;
        easing: ease-in-out-quad;
    }
    // animate height {
    //     duration: 400ms;
    //     easing: ease-in-out-quad;
    // }
    // animate opacity {
    //     duration: 400ms;
    //     easing: ease-in-out-quad;
    // }

    Rectangle {
        width: 100%;
        height: 100%;
        background: transparent;

        Rectangle {
            x: 1px;
            y: 1px;
            width: parent.width - 2px;
            height: parent.height - 2px;
            background: #1e1e2e;
            clip: true;

            Image {
                source: file-url;
                width: 100%;
                height: 100%;
                image-fit: cover;
            }

            Rectangle {
                visible: is-video;
                x: parent.width - 42px;
                y: 10px;
                width: 32px;
                height: 32px;
                border-radius: 6px;
                background: #2c2c2c;
                opacity: 0.5;

                Image {
                    source: @image-url("../../../../assets/icons/play-triangle.svg");
                    width: 14px;
                    height: 14px;
                    x: (parent.width - 14px) / 2;
                    y: (parent.height - 14px) / 2;
                }
            }

            ta := TouchArea {
                clicked => { root.clicked(); }
            }
        }
    }
}
