import { WallpaperItem, Picker } from "./picker/picker.slint";

export { WallpaperItem }
export global WallpaperPickerAdapter {
    in-out property <bool> is-ready;
    callback escape-pressed;
}

export component WallpaperPickerWindow inherits Window {
    background: #10101035;
    no-frame: true;

    forward-focus: p;

    touch_area := TouchArea {
        opacity: touch_area.has-hover ? 1.0 : 0.999;
        p := Picker {
            width: 100%;
            height: 100%;

            escape-pressed => {
                WallpaperPickerAdapter.escape-pressed();
            }
        }
    }
}
