import { WallpaperItem, Picker } from "./picker/picker.slint";

export { WallpaperItem }
export global WallpaperPickerAdapter {
    in-out property <int> render-trigger;
    callback escape-pressed;
}

export component WallpaperPickerWindow inherits Window {
    background: #10101035;
    no-frame: true;

    forward-focus: p;

    TouchArea {
        opacity: WallpaperPickerAdapter.render-trigger == 0 ? 0.999 : 1.0;
        p := Picker {
            width: 100%;
            height: 100%;

            escape-pressed => {
                WallpaperPickerAdapter.escape-pressed();
            }
        }
    }
}
